Test suite for CSV loader
Raphtory/docbrown pull request #35
Opened 2023-02-15 16:35 UTC by rachchan

`&self.test`

2023-02-16 10:29 UTC, iamsmkr requested changes

2023-02-16 11:13 UTC, rachchan commented on docbrown/db/src/loaders.rs
> +        assert_eq!(g.edges_len(), 701);
it needs it to assert that the number of edges is not 701

2023-02-16 15:59 UTC, iamsmkr requested changes

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/loaders.rs
> +        assert_ne!(g.edges_len(), 701);
This assertion is never reached, right?

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/loaders.rs
> +        // todo: move file path to data module
One todo per test is enough

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/loaders.rs
> +        // todo: move file path to data module
One todo per test is enough

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/loaders.rs
> +    }
Probably write a test with a file with a delimiter other than ','. For example, space?

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/loaders.rs
> +        csv_loader
Since this piece of code is common across all the tests, we can move it to a function now!

2023-02-16 15:59 UTC, iamsmkr commented on examples/src/bin/lotr/main.rs
> +            .set_delimiter(delimiter)
Create an api `set_delimiter_str` that takes `delimiter_string` directly and creates `delimiter` and passes it to `set_delimiter` on our behalf

2023-02-16 15:59 UTC, iamsmkr commented on docbrown/db/src/graphdb.rs
> +        let data_dir: PathBuf = [env!("CARGO_MANIFEST_DIR"), "resources/withheader/lotr.csv"]
We probably don't need to create separate directories for files of each type. Just name them accordingly. For instance `lotr-with-header.csv`

2023-02-17 15:28 UTC, iamsmkr approved these changes
Perfecto

2023-02-17 15:29 UTC, merged